if(EXISTS "/home/leonid/Рабочий стол/Projects/PetProjects/CppQt/SurveillanceTracker/Tests/TestFilters/TestFilters[1]_tests.cmake")
  include("/home/leonid/Рабочий стол/Projects/PetProjects/CppQt/SurveillanceTracker/Tests/TestFilters/TestFilters[1]_tests.cmake")
else()
  add_test(TestFilters_NOT_BUILT TestFilters_NOT_BUILT)
endif()
